---
name: Continuous integration

on:

  pull_request:
    branches:
      - main
    paths:
      - config/**
      - package.json
      - pnpm-lock.yaml
      - .readme.md
      - .github/workflows/ci.yml
  push:
    paths:
      - config/**
      - package.json
      - pnpm-lock.yaml
      - .readme.md
      - .github/workflows/ci.yml

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  issues: write
  pull-requests: write
  checks: write

jobs:
  # lint:
  #   permissions:
  #     actions: read
  #     contents: read
  #     issues: write
  #     pull-requests: write
  #     statuses: write
  #   uses: ./.github/workflows/lint-package.yml
  #   secrets: inherit

  npmJS:
    environment: npm
    runs-on: ubuntu-latest
    permissions:
      actions: read
      deployments: write
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:

    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - uses: IT-Service-NPM/.github/.github/actions/setup@main
      with:
        node-version: "24.x"

    - uses: cycjimmy/semantic-release-action@v6
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
